Repository sulu/SuluCommunityBundle, pull requests merged in 2020-08, with the labels that each got.

#129 Escape controller FQCN in render_esi call in docs
  Resources/doc/4-login.md
Labels: bug

#130 Add key to generate role
  Command/InitCommand.php
  Resources/doc/2-setup-webspace.md
Labels: enhancement

#131 Fix completion listener and complation validator services
  EventListener/CompletionListener.php
  Resources/doc/11-completion.md
Labels: bug

#132 Check for firewall name in completion listener
  EventListener/CompletionListener.php
  Resources/config/services.xml
Labels: bug, enhancement

#133 Fix permissions for generated role in sulu 2.2
  Command/InitCommand.php
  Resources/config/services.xml
Labels: bug
